"""empty message

Revision ID: 20c1acd9916a
Revises: ede45a6d0729
Create Date: 2021-03-25 00:55:00.726057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c1acd9916a'
down_revision = 'ede45a6d0729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('qualification', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'qualification')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
