"""empty message

Revision ID: 2b6c9f962a7d
Revises: 20c1acd9916a
Create Date: 2021-03-25 01:02:49.018014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6c9f962a7d'
down_revision = '20c1acd9916a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_datetime', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_datetime')
    # ### end Alembic commands ###
